# Security Review Workflow
name: security-review
description: "Expert security audit focused on OWASP Top 10, injection attacks, authentication flaws, data exposure, cryptography issues, and access control violations. Runs AFTER code-review as the second pass in dual-pass review process."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{implementation_artifacts}"
sprint_status: "{implementation_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/security-review"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"
template: false

variables:
  # Project context
  project_context: "**/project-context.md"
  story_dir: "{implementation_artifacts}"

# Smart input file references
input_file_patterns:
  architecture:
    description: "System architecture for security context"
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/*.md"
    load_strategy: "FULL_LOAD"
  security_docs:
    description: "Security documentation if exists"
    whole: "{project-root}/docs/*security*.md"
    load_strategy: "FULL_LOAD"

# Prerequisites - must run after code-review
prerequisites:
  - workflow: "code-review"
    status: "passed"
    message: "Security review requires code-review to pass first"

standalone: true
